### PR TITLE
Problem types auto-discovery

### PR DESCRIPTION
**Pull request by nrybowski**
This PR adds the feature described in #864.

### TODO
- [x] Base function to get tupple of problem name and problem class
- [x] Generic function to get all default problem types available
- [x] Get problem types added by a plugin
- [x] Handle displayable problem types

### CODE REVIEW

**Review by anthonygego — COMMENTED** [review]
The code looks good to me, but I'm not sure to get the real advantage of inspecting the two base modules as the hardcoded list can be returned by the new ``get_default_XXX_types`` functions (the list will remain small).

How are plugins supposed to get advantage of these changes then ?

**Comment by nrybowski** [comment]
Lines https://github.com/UCL-INGI/INGInious/pull/861/files/0cbb49dadaa831dc57d0d6ba982bb300009efd39#diff-1d137a6d9bae298e93e0d36cb3b8e2ef0cc297051516f2c5bd5ea479d9aa257bR239-R246 become something like
```
all_pbl_types = get_default_problem_type()
for plugin in plugins:
    pbl_types = get_problems_type(plugin)
    all_pbl_type.update(pbl_types)
```
and the plugin is immediately loaded.

**Comment by anthonygego** [comment]
OK. Maybe we should take the opportunity to update the code so that the frontend and agents load the problem types this way and make the current ``add_problem_type`` function a dummy function ? This would be more coherent. What do you think ?

**Comment by nrybowski** [comment]
Rebased on 0959be6d8127e5a867a3e190423897069bf2eae9.

The PR is ready for merge.

**Comment by anthonygego** [comment]
Did we conclude anything from my previous comment ? If you feel the same way, do you plan to do this in another PR and let me merge this one in the meanwhile ?

**Comment by nrybowski** [comment]
It seems I lost the commit implementing this during my rebase... I should be able to get it back from a local branch.

**Comment by nrybowski** [comment]
Here is the missing commit 316841981eb03b197f85107be53b9135d0a2ba71. I pushed from the wrong branch yesterday ..

**Comment by anthonygego** [comment]
LGTM.

**Pull request merged**
