### PR TITLE
Add cursor:pointer for .list-group-item

### PR DESCRIPTION
**Pull request by bogem**
On some machines the cursor isn't correct

### CODE REVIEW

**Comment by GuillaumeDerval** [comment]
This is more a problem with BootStrap than with our theme; moreover, it shouldn't be a pointer when the list-item does not hold a link.

Can you be more specific on the affected platforms/browsers/pages?

**Comment by bogem** [comment]
But where it can hold not a link?
I saw it on some student's PC. It was Windows, but I don't remember the browser. Chrome or Opera.

**Comment by bogem** [comment]
I don't have this issue on my macOS with last Chrome

**Comment by anthonygego** [comment]
There are several list group items that are not links such as in the "Submitting as" list in the task page or the student list in classroom pages.

**Comment by GuillaumeDerval** [comment]
Closing this for now. If you spot the affected browser, please open a new issue :-)

**Pull request closed without merging**
