### PR TITLE
Remove Protocol from get_homepath functions

### PR DESCRIPTION
**Pull request by pchaow**
Link to issue #656 

I create this pull request to show crude solution to remove protocol from get_homepath functions

### CODE REVIEW

**Comment by Drumor** [comment]
Hello,

Thank u for this contribution. Could you squash your commits into one? Thx!

**Comment by pchaow** [comment]
Ok, I’ll try another solution

**Comment by anthonygego** [comment]
To be clearer, the application itself (and thus the wsgi context) should be aware of the protocol used by the client because several features rely on this : url generation (that should be replaced by the more idiomatic ``url_for``in the future btw), LTI and the social apps auth method that relies on OAuth 1 or 2. Those protocols use URLs to sign their messages.

Therefore the ProxyFix middleware seems to be the best solution to solve this issue properly. As it is not recommended to enable this by default, I suggest to include it as an opt-in in ``inginious-webapp`` file, and to fetch the function arguments via the configuration file.

**Comment by pchaow** [comment]
Thanks, I've tried proxyfix and it's work for me. I'll add some configuration

**Pull request closed without merging**
