### PR TITLE
Added Nginx documentation

### PR DESCRIPTION
**Pull request by izayoi-ami**
A quick setup for Nginx is written.

### CODE REVIEW

**Comment by izayoi-ami** [comment]
ok to test

**Comment by anthonygego** [comment]
Configuring the webserver as a proxy to the the webapp application does not seem to be a good idea. You'll probably be able to distribute the load among several instances but performance will be worse as you'll still use the Python-integrated HTTP stack and thus only add overhead, except for the static files.

To achieve much more performance, you should probably look at ways to use FastCGI or WSGI with Nginx.

**Comment by GuillaumeDerval** [comment]
Web.py provides a small cookbook about nginx: http://webpy.org/cookbook/fastcgi-nginx

It's probably a good starting point :-)

**Comment by GuillaumeDerval** [comment]
Closing this for now.

**Pull request closed without merging**
