### PR TITLE
Added domain for Google OAuth plugin

### PR DESCRIPTION
**Pull request by tijcolem**
This is great you added the Google OAuth plugin. I added support to restrict it to allow a defined domain (e.g. 'colorado.edu').

### CODE REVIEW

**Comment by tijcolem** [comment]
ok to test

**Comment by anthonygego** [comment]
Thanks ! Can you sign the CLA for us to be able to merge ? https://cla-assistant.io/UCL-INGI/INGInious?pullRequest=273

**Comment by tijcolem** [comment]
Sorry about that, I thought I signed the CLA. I signed it just now.

**Comment by anthonygego** [comment]
Actually that's because the committer email adress email is not your actual one, so Github does not make the link. I confirm that the CLA is signed :-)

**Pull request merged**
