### PR TITLE
More stability in LdapAuthMethod/UserManager.get_users_info

### PR DESCRIPTION
**Pull request by bogem**

### CODE REVIEW

**Comment by bogem** [comment]
ok to test

**Comment by bogem** [comment]
test this please

**Comment by bogem** [comment]
OMG I can't find out how to use this test bot.
Please explain me😅

**Comment by GuillaumeDerval** [comment]
> I will only listen to repo owners
;-)

(it is currently broken, the tests are always launched (they shouldn't for security reasons))

**Comment by bogem** [comment]
Ah, okay.
Somehow I thought it listens also to PR owners😅

**Comment by anthonygego** [comment]
LGTM

**Pull request merged**
