### PR TITLE
Updating state of user tasks

### PR DESCRIPTION
**Pull request by Drumor**
It's more than probably not mergeable as it is but I'd like to know if I understood well the #434 issue? Is it possible to get extra information about this feature request? Thx

### CODE REVIEW

**Comment by anthonygego** [comment]
I'd rather have this in a POST method with a confirmation via a modal as for other critical features such as removing a student from the course, to avoid any wrong manipulation. I don't think it is neccesary to put the POST processing in another page, the routing dictionary is already long enough. You can just check for the form submission in the concerned page and call the appropriate function at that time. This will avoid to play with redirects too.

**Comment by Drumor** [comment]
I think i have made changes you asked for.

**Comment by Drumor** [comment]
I need to review if all is okay after rebase of master and also change page situation of button

**Comment by Drumor** [comment]
I think i've done here.

**Pull request merged**
